<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WzComparerX.Core\WzComparerX.Core.csproj" />
    <ProjectReference Include="..\WzComparerX.Rendering\WzComparerX.Rendering.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
